"""Build gate: every number in the manuscript must trace to an analysis output, and stay traced.

What this checks, in order of how much damage the failure would do:

  1. VENUE FACTS. City, country, month, page limit, workshop name. These are typed once, print on
     every page, and are structurally invisible to a number-tracing gate, which is exactly how an
     invented venue reached a submitted PDF on an earlier paper in this portfolio. Each is asserted
     positively AND with a negative clause naming what must not come back.
  2. MACRO PROVENANCE. Every macro used in the manuscript exists in the generated macros.tex, and
     every macro's value equals the value in the analysis JSON right now. A stale macro is the
     failure mode that survives a re-run.
  3. NO HAND-TYPED NUMBERS. Any bare numeral in the prose that is not inside a macro, a \\lit{} (a
     value quoted from a cited source), or the structural allowlist is a defect.
  4. RETIRED CLAIMS. Anything a review round removed must not come back. Loaded from
     notes/retired_claims.json so that recording a retraction arms the gate against it.
  5. NEGATIVE CLAUSES. Statements this paper must NOT make, because the data does not support them.
  6. PLACEHOLDERS. No PLACEHOLDER, TODO or MEASURE marker may survive into a build.

Run the LaTeX build BEFORE this, or the staleness check fires on macros you just regenerated.
"""
from __future__ import annotations

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
PAPER = os.path.join(ROOT, "paper")

FAILS: list = []
OKS = [0]


def check(name: str, cond: bool, detail: str = ""):
    if cond:
        OKS[0] += 1
    else:
        FAILS.append("%s%s" % (name, (": " + detail) if detail else ""))


def read(p: str) -> str:
    with open(os.path.join(PAPER, p), encoding="utf-8") as fh:
        return fh.read()


def main() -> int:
    main_tex = read("main.tex")
    body = read("body.tex")
    abstract = read("abstract.tex")
    macros_src = read("macros.tex")
    prose = body + "\n" + abstract
    # Hand-written fragments are held to the no-typed-numbers rule. Machine-generated ones are not,
    # because every value in them came from the analysis JSON milliseconds earlier; instead the gate
    # asserts they really are machine-generated, so a hand-edited table cannot slip through by
    # sitting in a filename that looks generated.
    GENERATED = ("tab_rq1.tex", "tab_rq2.tex", "txt_diffsize.tex")
    # txt_abstract_rq2.tex was retired at camera-ready: the shortened abstract no longer inputs
    # it, and a prose file nothing renders is a place for retired claims to hide.
    HANDWRITTEN = ("txt_rq2.tex", "txt_conclusion.tex")
    generated_blob = ""
    for extra in GENERATED + HANDWRITTEN:
        p = os.path.join(PAPER, extra)
        if not os.path.exists(p):
            continue
        with open(p, encoding="utf-8") as fh:
            t = fh.read()
        if extra in GENERATED:
            check("generated.stamped." + extra,
                  t.lstrip().startswith("% GENERATED by code/tables.py"),
                  "exempted from the typed-number check but carries no generated-by stamp")
            generated_blob += "\n" + t
        else:
            prose += "\n" + t
    # Generated fragments still take part in every other check.
    all_tex = prose + "\n" + generated_blob

    # ---------- 0. source integrity: control characters and de-backslashed macros ----------
    # A shell one-liner turned "\S\ref{...}" into "\S", a literal carriage return, and "ef{...}".
    # LaTeX reported ZERO errors, because \S is valid and "ef" is just letters, so the garbage
    # rendered onto the page and every other gate here passed. Only real escapes damage this way
    # (\r \n \t \b \f \a \v \0 \x \N \u \U), which is what makes it selective and silent.
    for fname in ("main.tex", "body.tex", "abstract.tex", "macros.tex") + GENERATED + HANDWRITTEN:
        fp = os.path.join(PAPER, fname)
        if not os.path.exists(fp):
            continue
        with open(fp, encoding="utf-8", newline="") as fh:
            raw = fh.read()
        # CRLF is a normal Windows line ending. A LONE carriage return, not followed by a newline,
        # is the signature of an eaten \r escape sitting inside a line.
        ctrl = sorted({c for c in raw if ord(c) < 32 and c not in "\n\t\r"})
        lone_cr = len(re.findall(r"\r(?!\n)", raw))
        check("integrity.no_control_chars." + fname, not ctrl and lone_cr == 0,
              "control characters %s, %d lone CR; a shell escape has corrupted this file"
              % ([hex(ord(c)) for c in ctrl], lone_cr))
        # A macro that lost its leading backslash leaves its tail as a bare word before a brace.
        # Comparing COUNTS is what makes this work: "exttt{" is a legitimate substring of every
        # "\texttt{", so the fragment is only evidence of damage when it appears more often than
        # the intact macro does.
        # `intact` is a REGEX, because a fragment can be legitimately contained in more than one
        # macro: "ewcommand" sits inside \newcommand and \renewcommand alike, and pinning only the
        # first made the guard fire on correct source.
        for intact, frag in ((r"\\(?:page)?ref\{", "ef{"), (r"\\textbf\{", "extbf{"),
                             (r"\\textit\{", "extit{"), (r"\\texttt\{", "exttt{"),
                             (r"\\(?:re)?newcommand", "ewcommand"),
                             (r"\\label\{", "abel{"), (r"\\(?:cite|acmConference)\{", "ite{"),
                             (r"\\emph\{", "mph{")):
            extra = raw.count(frag) - len(re.findall(intact, raw))
            check("integrity.no_debackslashed." + fname + "." + frag.strip("{"), extra <= 0,
                  "%r appears %d time(s) more than %s, which is what an eaten escape looks like"
                  % (frag, extra, intact))

    # ---------- 1. venue facts ----------
    # Fetched 2026-07-30 from conf.researchr.org/home/povc-2026 and /track/povc-2026/povc-2026-papers.
    # Negative venue checks run against the UNCOMMENTED source only. The preamble documents which
    # strings are wrong and why, and a naive scan of the raw file finds the wrong string inside the
    # comment that warns about it.
    main_live = re.sub(r"(?m)^\s*%.*$", "", main_tex)
    main_live = re.sub(r"(?<!\\)%.*", "", main_live)
    # POSITIVE checks also run against main_live. Against the raw file they are satisfied by the
    # preamble comment that documents the correct values, so replacing the real \acmConference line
    # with a wrong city still passed. An injected "Seoul, South Korea" was caught only by a negative
    # clause that happened to name Seoul, which would not have covered an arbitrary wrong city.
    # City and dates are asserted ON THE \acmConference COMMAND, not file-wide. The rights block
    # added \acmBooktitle, which repeats "Munich, Germany" and the dates, so a file-wide substring
    # test would be satisfied by the booktitle while \acmConference carried a wrong city. The
    # selftest's wrong_city injection went from CAUGHT to MISSED the moment the block was inserted,
    # which is how this was found: a gate can be silently weakened by content added elsewhere.
    conf = re.search(r"\\acmConference(\[[^\]]*\])?(\{(?:[^{}]|\{[^{}]*\})*\}){3}", main_live)
    check("venue.conference_line_present", conf is not None,
          "no \\acmConference command found, so city and dates are unasserted")
    conf_txt = conf.group(0) if conf else ""
    check("venue.city", "Munich, Germany" in conf_txt)
    check("venue.dates", "October 12--16, 2026" in conf_txt)
    check("venue.year", r"\acmYear{2026}" in main_live)
    # CAMERA-READY venue identity. Until the rights block arrived these checks pinned the venue's
    # WEB BRANDING ("PROMPTOPS 2026: Engineering Reliable AI-Augmented Software Development") and
    # carried a negative clause asserting "International Workshop on" never appears, because that
    # phrase had been invented at build time on an earlier paper. The ACM eRights system then
    # supplied the official proceedings title, which contains exactly that phrase. Both facts were
    # true of different objects, and a clause pinned to WORDING cannot tell "the author invented
    # this" from "the publisher assigned this". So the negative clause is
    # RETIRED and the positive checks now assert equality with the strings ACM supplied, verbatim,
    # for paper asews26povcmain-p16-p on 2026-08-31.
    check("venue.acm_booktitle",
          "Proceedings of the 1st International Workshop on PromptOps and Vibe Coding "
          "(POVC '26), October 12--16, 2026, Munich, Germany" in main_live,
          "the ACM booktitle must match the rights block verbatim")
    check("venue.acm_shortname", "\\acmConference[POVC '26]" in main_live,
          "the ACM short name must match the rights block verbatim")
    check("venue.doi", r"\acmDOI{10.1145/3843779.3844636}" in main_live,
          "the DOI must match the one ACM assigned; a wrong DOI is unrecoverable after publication")
    check("venue.isbn", r"\acmISBN{979-8-4007-2991-1/2026/10}" in main_live)
    check("venue.cc_by", r"\setcopyright{cc}" in main_live and r"\setcctype{by}" in main_live,
          "the licence must be the CC-BY the rights agreement granted")
    # The submission-era placeholders must never come back: they suppress the ACM reference block
    # and the copyright notice, which a camera-ready is required to print.
    for bad, why in ((r"\setcopyright{none}", "interim placeholder"),
                     ("printacmref=false", "suppresses the required ACM reference block"),
                     (r"\renewcommand\footnotetextcopyrightpermission", "suppresses the notice")):
        check("venue.no_placeholder." + bad.strip("\\")[:18],
              bad not in main_live, why)
    # Negative clauses: each of these was either invented on an earlier paper or is simply wrong.
    for bad in ("Seoul", "South Korea", "November 2026", "Rio de Janeiro, Brazil}"):
        check("venue.not_" + bad.split(",")[0].replace(" ", "_").lower(),
              bad not in main_live, "wrong venue string present")
    # Assert the actual documentclass options, not the mere presence of the words. Both "anonymous"
    # and "review" occur in the preamble comment explaining the blinding decision, so a substring
    # test over the file passed even after the options themselves were stripped.
    dc = re.search(r"\\documentclass\[([^\]]*)\]\{acmart\}", main_live)
    opts = {o.strip() for o in dc.group(1).split(",")} if dc else set()
    # CAMERA-READY (accepted 2026-08-23): the submission-era check required {review, anonymous};
    # the camera-ready must be the opposite. Positive: sigconf present. Negative: neither review
    # nor anonymous may return, and the author block must exist (an accepted paper with no author
    # is a publishable defect the class will not warn about).
    check("venue.cr_not_anonymous", "sigconf" in opts and not ({"review", "anonymous"} & opts),
          "documentclass options are %s; camera-ready must drop review/anonymous" % sorted(opts))
    check("venue.cr_author_block", r"\author{Simarjot Khanna}" in main_live
          and "Independent Researcher" in main_live,
          "camera-ready must carry the author block")
    # Artifact availability: an availability claim with no reachable link is a documented
    # rejection ground. Positive: the live URL appears in the prose that reaches the PDF.
    # Negative: the submission-era phrase must not come back, because it was true only while
    # there was nothing to link to.
    arturl = "github.com/s1mar/chat-template-drift"
    check("artifact.url_present", arturl in body or arturl in main_live,
          "no artifact URL in body/main; an availability claim with no link is fatal")
    check("artifact.no_on_acceptance_phrase",
          "released permanently on acceptance" not in prose,
          "submission-era availability phrasing must not survive into the camera-ready")

    # ---------- 1c. CCS block ----------
    # The CCS block is metadata that NOTHING else here traces: every concept_id is syntactically
    # fine and corresponds to no number, so a wrong one indexes the paper under the wrong concept
    # in the Digital Library while page 1 prints the right words. This block had exactly that
    # defect, copied from a sibling paper: the configuration-management concept carried
    # 10011007.10011074.10011111.10011113, which is "Software evolution" in ACM's taxonomy. The
    # values below were GENERATED by ACM's own CCS tool (dl.acm.org/ccs) on 2026-08-31, which emits
    # the XML and the \ccsdesc lines together, and are pinned here so the two cannot drift again.
    CCS = [("10011007.10011074.10011099",
            "Software and its engineering~Software verification and validation", "500"),
           ("10011007.10011006.10011071",
            "Software and its engineering~Software configuration management and version "
            "control systems", "500")]
    for cid, desc, sig in CCS:
        block = re.search(r"<concept>\s*<concept_id>" + re.escape(cid)
                          + r"</concept_id>\s*<concept_desc>([^<]*)</concept_desc>\s*"
                          r"<concept_significance>(\d+)</concept_significance>", main_tex, re.S)
        check("ccs.pair." + cid, block is not None,
              "no <concept> with id %s; the CCS block must match the generated one" % cid)
        if block:
            check("ccs.desc." + cid, " ".join(block.group(1).split()) == desc,
                  "id %s is paired with %r, generated block says %r"
                  % (cid, block.group(1), desc))
            check("ccs.sig." + cid, block.group(2) == sig,
                  "id %s has significance %s, generated block says %s"
                  % (cid, block.group(2), sig))
        # The printed \ccsdesc must carry the SAME weight as the XML, or the page and the DL
        # record disagree about how central the concept is.
        check("ccs.ccsdesc." + cid,
              ("\\ccsdesc[%s]{%s}" % (sig, desc)) in " ".join(main_tex.split()),
              "no \\ccsdesc[%s] for %r matching the generated block" % (sig, desc))
    # Nothing may reintroduce the wrong identifier this block used to carry.
    check("ccs.no_retired_id", "10011074.10011111.10011113" not in main_tex,
          "that id is ACM's 'Software evolution', not configuration management")

    # ---------- 2. macro provenance ----------
    defined = dict(re.findall(r"\\newcommand\{\\(\w+)\}\{(.*?)\\xspace\}", macros_src))
    titles = re.findall(r"\\newcommand\{\\(\w+)\}\{(.*?)\}\s*$", macros_src, re.M)
    # Macro-usage is checked over EVERYTHING, generated tables included: a table referencing a macro
    # the pipeline never emitted is exactly as broken as prose doing it.
    used = set(re.findall(r"\\([A-Z][A-Za-z]+)\b", all_tex))
    known_latex = {"NFrame"}  # placeholder, real filter below
    latex_builtins = {
        "Undefined", "LaTeX", "BibTeX", "TeX", "Jinja", "It", "The", "A", "In", "We", "Of", "That",
        "This", "Beyond", "Most", "Textual", "PromptOps", "Six", "Three", "Prompts", "Vibe",
        "Dependency", "Work", "Pinning", "Replayed", "Reading", "History", "An", "Every", "All",
        "Popularity", "Repair", "Rendering", "Local", "Many", "Chat", "Between", "Open", "There",
        "Change", "Serving", "PDF", "Holm", "McNemar", "GPU", "Hub", "Python", "Git", "SHA",
        "Qwen", "Phi", "Mistral", "Meta", "Llama", "Jinja", "PctSuppressed",
    }
    for u in sorted(used):
        if u in latex_builtins or len(u) <= 2:
            continue
        if u in defined or any(t[0] == u for t in titles):
            continue
        # only flag things that look like our generated macro names
        if re.match(r"^(N|Pct|Med|Max|Min|Cost|Floor|Div|Res|PHolm|Naive|Render|Suppressed|"
                    r"Settled|Paper|Probe|Stranded)", u):
            check("macro.defined." + u, False, "used in prose but not defined in macros.tex")

    # Values must equal the analysis output right now.
    with open(os.path.join(DATA, "rq1.json"), encoding="utf-8") as fh:
        rq1 = json.load(fh)
    s1 = rq1["summary"]
    expect = {
        "NFrame": s1["n_frame"], "NDrifted": s1["n_drifted"], "PctDrifted": s1["pct_drifted"],
        "NBehavioural": s1["n_behavioural"], "PctBehFrame": s1["pct_behavioural_of_frame"],
        "NEvents": s1["n_pairs"], "NEventsDecidable": s1["n_pairs_decidable"],
        "NEventsBeh": s1["n_pairs_behavioural"], "PctEventsBeh": s1["pct_pairs_behavioural"],
        "NEventsCosmetic": s1["n_pairs_cosmetic"],
        "PctEventsWeightSilent": s1["pct_pairs_weight_silent"],
        "MedianDaysFirstChange": s1["median_days_to_first_change"],
        "PctBehSettledFrame": s1["pct_behavioural_settled_of_frame"],
        "PctBehWeightSilent": s1["pct_behavioural_weight_silent_of_behavioural"],
    }
    p3 = os.path.join(DATA, "rq3.json")
    if os.path.exists(p3):
        with open(p3, encoding="utf-8") as fh:
            r3 = json.load(fh)
        expect.update({"NaiveAlerts": r3["naive_alerts"], "RenderAlerts": r3["render_alerts"],
                       "SuppressedAlerts": r3["suppressed_as_cosmetic"],
                       "PctSuppressed": r3["pct_suppressed"],
                       "CostComputeMs": r3["cost_ms_compute_only"],
                       "NStranded": r3["n_stranded_repos"]})
        # The probe count is spelled as the word "six" in prose (invisible to the digit scan), so
        # the analysis-side fact is asserted here instead: if the probe set ever changes, this
        # fires and every "six" in the prose is reviewed by hand.
        check("probes.count_is_six", r3.get("n_probes") == 6,
              "rq3.json says %r probes; the prose spells six" % r3.get("n_probes"))
    # RQ2 value tracing (cr3 review panel, 2026-08-30): this gate previously traced RQ1 and RQ3
    # macros only, so a stale rq2.json would have left every RQ2 number in the paper wrong while
    # the gate printed a clean pass. Trace the headline RQ2 macros and spot-check the generated
    # table's cells against the same source.
    p2 = os.path.join(DATA, "rq2.json")
    if os.path.exists(p2):
        with open(p2, encoding="utf-8") as fh:
            rq2 = json.load(fh)
        expect.update({"NExecEpisodes": rq2["n_episodes"],
                       "NExecTruncated": rq2["truncated"],
                       "NSigRes": rq2["n_family_sig_resolution"],
                       "NSigContract": rq2["n_family_sig_contract"],
                       "NFamily": sum(1 for r in rq2["family"] if r.get("informative", True))})
        phi = rq2["models"].get("phi3:mini", {})
        if phi:
            vs = phi["versions"]
            expect.update({"ConPhiA": vs[0]["contract_pct"], "ConPhiB": vs[1]["contract_pct"],
                           "ConPhiC": vs[2]["contract_pct"], "ResPhiA": vs[0]["resolved_pct"],
                           "FloorPhi": phi["replication"]["response_divergence_pct"]})
        tab2 = ""
        t2p = os.path.join(PAPER, "tab_rq2.tex")
        if os.path.exists(t2p):
            with open(t2p, encoding="utf-8") as fh:
                tab2 = fh.read()
        check("tab_rq2.exists", bool(tab2), "generated table missing")
        missing = []
        for mod, mm in rq2["models"].items():
            for v in mm["versions"]:
                for val in (v["resolved_pct"], v["contract_pct"]):
                    if ("%s" % val) not in tab2:
                        missing.append("%s %s" % (mod, val))
        check("tab_rq2.cells_match_rq2json", not missing,
              "table cells absent for: %s (tables.py and make_macros.py read the same json "
              "independently; a partial re-run desynchronises them)" % missing[:4])
    for k, v in expect.items():
        check("macro.value." + k, k in defined and defined[k] == str(v),
              "macros.tex has %r, analysis says %r" % (defined.get(k), str(v)))

    # ---------- 3. no hand-typed numbers ----------
    stripped = prose
    stripped = re.sub(r"\\lit\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\}", " ", stripped)
    # Allow an optional argument: \includegraphics[width=\columnwidth]{fig1.pdf} left "1." behind
    # when the pattern assumed the braces followed the command name directly.
    stripped = re.sub(r"\\(?:label|ref|cite|input|includegraphics|newcommand)"
                      r"(?:\[[^\]]*\])?\{[^}]*\}", " ", stripped)
    stripped = re.sub(r"%.*", " ", stripped)
    stripped = re.sub(r"\\[A-Za-z]+", " ", stripped)          # macros themselves
    stripped = re.sub(r"\b(?:SHA|sha)-?256\b", " ", stripped)
    # Model identifiers are proper nouns, not measurements. "Qwen2.5-7B-Instruct" is a name, and
    # without this the gate reports 2.5 and 7 as untraced numbers and trains you to ignore it.
    stripped = re.sub(r"(?:Qwen|Phi|Mistral|Llama|deepseek-coder|HumanEval|GPT)[\w.\-+]*",
                      " ", stripped)
    stripped = re.sub(r"\bv\d+(?:\.\d+)*\b", " ", stripped)
    # RQ1/RQ2/RQ3 are section labels, not measurements; added at camera-ready when the admin asked
    # for explicit RQ linkage. Only the exact token is stripped, so "RQ12" or a real numeral after
    # "RQ" still trips the gate.
    stripped = re.sub(r"\bRQ\d\b", " ", stripped)
    # Typed constants added at camera-ready, each a fact rather than a result: the frame-draw date
    # (provable from the shipped preregistration, frozen 2026-07-30), the release tag cr-1.0, and
    # the 1536-token generation cap (the harness constant in run_exec.py / the README command).
    # Each is stripped as its exact token only, so any other typed number still trips the gate.
    stripped = re.sub(r"\b2026-07-30\b", " ", stripped)
    stripped = re.sub(r"\bcr-1\.0\b", " ", stripped)
    stripped = re.sub(r"\b1536-token\b", " ", stripped)
    allow = {"6", "10", "000", "2", "3", "1", "0", "05", "5", "4"}  # structural: probe count, etc.
    bad = [t for t in re.findall(r"\d[\d.,]*", stripped) if t not in allow]
    check("no_hand_typed_numbers", not bad, "bare numerals in prose: %s" % sorted(set(bad))[:12])

    # ---------- 4. retired claims ----------
    rc = os.path.join(ROOT, "notes", "retired_claims.json")
    if os.path.exists(rc):
        with open(rc, encoding="utf-8") as fh:
            retired = json.load(fh)
        for r in retired:
            check("retired." + r["id"], not re.search(r["pattern"], all_tex, re.I | re.S),
                  r["reason"])

    # ---------- 5. negative clauses ----------
    neg = [
        ("no_maintainer_blame",
         r"maintainers?\s+(?:are|were)\s+(?:careless|negligent|at fault)",
         "the paper explicitly does not claim maintainers acted wrongly"),
        ("no_hosted_api_claim",
         r"(?:OpenAI|Anthropic|hosted commercial API)s?\s+(?:also\s+)?(?:change|drift)",
         "hosted APIs are not observable by this method; the threats section says so"),
        ("no_causal_popularity",
         r"popularity\s+causes\s+drift",
         "no causal claim about popularity is identified by this design"),
        # `changes?` not `change`: the injected sentence read "every template edit changes
        # behaviour", and a pattern requiring whitespace straight after "change" did not match it.
        # A negative clause that misses the plural is a negative clause that does nothing.
        ("no_all_edits_matter",
         r"(?:every|all)\s+template\s+(?:edits?|changes?)\s+(?:changes?|alters?)\s+behaviour",
         "about half of decidable edits are cosmetic; this overclaims"),
    ]
    for nid, pat, why in neg:
        check("negative." + nid, not re.search(pat, all_tex, re.I), why)

    # ---------- 6. placeholders ----------
    for marker in ("PLACEHOLDER", "TODO", "MEASURE:", "XXX", "FIXME"):
        check("placeholder." + marker.strip(":"), marker not in all_tex,
              "%s survives in the manuscript" % marker)

    # ---------- report ----------
    print("consistency: %d checks passed, %d FAILED" % (OKS[0], len(FAILS)))
    for f in FAILS:
        print("   FAIL  %s" % f)
    return 1 if FAILS else 0


if __name__ == "__main__":
    sys.exit(main())
