"""Write paper/macros.tex from the analysis outputs.

`\\lit{}` in the manuscript marks a number quoted from a cited source; everything else must be a
macro defined here, which is what `code/consistency.py` checks.
"""
from __future__ import annotations

import json
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
OUT = os.path.join(ROOT, "paper", "macros.tex")

TITLE = ("Your Prompt Is Only Half the Prompt: Silent Chat-Template Drift in Open-Weight "
         "Model Repositories")


def esc(s: str) -> str:
    return s.replace("_", r"\_").replace("&", r"\&").replace("#", r"\#")


def main() -> int:
    lines = ["% GENERATED by code/make_macros.py. Do not edit by hand.",
             "% Every number in the manuscript resolves through one of these.",
             r"\newcommand{\PaperTitle}{%s}" % TITLE]

    def m(name: str, value, pct: bool = False):
        if value is None:
            raise SystemExit("macro %s is None: the analysis did not produce it" % name)
        v = ("%s" % value)
        lines.append(r"\newcommand{\%s}{%s\xspace}" % (name, v))

    with open(os.path.join(DATA, "rq1.json"), encoding="utf-8") as fh:
        rq1 = json.load(fh)
    s, meta = rq1["summary"], rq1["meta"]
    st = meta["status"]

    m("NCandidates", meta["n_candidates"])
    m("NIncludedTotal", meta["n_included_total"])
    m("NFrame", s["n_frame"])
    m("NGated", st.get("gated_or_missing", 0))
    m("NNoTemplateFile", st.get("no_template_file", 0))
    m("NNoTemplateRev", st.get("no_template_in_any_revision", 0))

    m("NDrifted", s["n_drifted"])
    m("PctDrifted", s["pct_drifted"])
    m("NBehavioural", s["n_behavioural"])
    m("PctBehFrame", s["pct_behavioural_of_frame"])
    m("PctBehDrifted", s["pct_behavioural_of_drifted"])
    m("NBehSettled", s["n_behavioural_settled"])
    m("PctBehSettledFrame", s["pct_behavioural_settled_of_frame"])
    m("NBehWeightSilent", s["n_behavioural_weight_silent"])
    m("PctBehWeightSilent", s["pct_behavioural_weight_silent_of_behavioural"])

    # Fixture sensitivity (cr3 review panel, 2026-08-30): the download ranking admits CI and test
    # fixtures (tiny/dummy/random checkpoints with heavy automated pull traffic). This is the ONE
    # place the fixture rule lives; the Threats sentence cites these macros rather than restating
    # the rule, so the two cannot drift apart.
    import re as _re
    _fix = _re.compile(r"trl-internal-testing/|tiny-random|/tiny-|dummy", _re.I)
    _keep = [r for r in rq1["repos"] if not _fix.search(r["mid"])]
    _kn = len(_keep)
    _kdec = [p for r in _keep for p in r["pairs"] if p["textual_change"] and p["decidable"]]
    m("NFixtures", s["n_frame"] - _kn)
    m("PctBehSettledNoFix",
      round(100.0 * sum(1 for r in _keep if r.get("any_behavioural_settled")) / _kn, 1))
    m("PctEventsBehNoFix",
      round(100.0 * sum(1 for p in _kdec if p["behavioural"]) / len(_kdec), 1))

    m("NEvents", s["n_pairs"])
    m("NEventsDecidable", s["n_pairs_decidable"])
    m("NEventsUndecidable", s["n_pairs_undecidable"])
    m("NEventsBeh", s["n_pairs_behavioural"])
    m("PctEventsBeh", s["pct_pairs_behavioural"])
    m("NEventsCosmetic", s["n_pairs_cosmetic"])
    m("NEventsWeightSilent", s["n_pairs_weight_silent"])
    m("PctEventsWeightSilent", s["pct_pairs_weight_silent"])
    m("MedianDaysFirstChange", s["median_days_to_first_change"])
    m("SettledDays", 30)

    mx = max(s["distinct_template_hist"], key=lambda k: int(k))
    m("MaxDistinctTemplates", mx)

    o = rq1.get("out_of_frame_summary") or {}
    if o:
        m("NOutOfFrame", o["n_frame"])
        m("PctOOFDrifted", o["pct_drifted"])
        m("PctOOFBeh", o["pct_behavioural_of_frame"])

    pd = s["probes_differing"]
    for k, v in pd.items():
        m("Probe" + "".join(p.capitalize() for p in k.split("_")), v)

    # ---- renderer validation gate ----
    vpath = os.path.join(DATA, "renderer_validation.json")
    if os.path.exists(vpath):
        with open(vpath, encoding="utf-8") as fh:
            vv = json.load(fh)
        checked = [r for r in vv if "skipped" not in r]
        m("NValidated", len(checked))
        m("NValidatedFailed", sum(1 for r in checked if not r["ok"]))

    # ---- RQ3 ----
    p3 = os.path.join(DATA, "rq3.json")
    if os.path.exists(p3):
        with open(p3, encoding="utf-8") as fh:
            rq3 = json.load(fh)
        m("NaiveAlerts", rq3["naive_alerts"])
        m("RenderAlerts", rq3["render_alerts"])
        m("SuppressedAlerts", rq3["suppressed_as_cosmetic"])
        m("PctSuppressed", rq3["pct_suppressed"])
        m("NStranded", rq3["n_stranded_repos"])
        m("MedianDaysStranded", rq3["median_days_to_first_behavioural"])
        m("CostComputeMs", rq3["cost_ms_compute_only"])
        m("NProbes", rq3["n_probes"])

    # ---- diff size does not predict behaviour ----
    dpath = os.path.join(DATA, "diffsize.json")
    if os.path.exists(dpath):
        with open(dpath, encoding="utf-8") as fh:
            d = json.load(fh)
        m("MedAbsLenCosmetic", d["median_abs_len_cosmetic"])
        m("MedAbsLenBehavioural", d["median_abs_len_behavioural"])
        m("MaxCosmeticLenChange", d["max_abs_len_cosmetic"])
        m("NBehZeroLenChange", d["n_behavioural_zero_len_change"])
        if d.get("auc_len_delta") is not None:
            m("DiffAUC", "%.2f" % d["auc_len_delta"])

    # ---- RQ2, only if it has been produced ----
    p2 = os.path.join(DATA, "rq2.json")
    if os.path.exists(p2):
        with open(p2, encoding="utf-8") as fh:
            rq2 = json.load(fh)
        m("NExecEpisodes", rq2["n_episodes"])
        m("NExecTruncated", rq2["truncated"])
        m("NExecRenderErrors", rq2["render_errors"])
        m("NCheckpoints", len(rq2["models"]))

        short = {"qwen2.5:7b-instruct": "Qwen", "phi3:mini": "Phi",
                 "deepseek-coder:6.7b-instruct": "DSCoder",
                 "mistral:7b-instruct-v0.2-q4_0": "Mistral", "llama3:latest": "Llama"}
        floors = []
        for model, mm in rq2["models"].items():
            tag = short.get(model, "M")
            m("Floor" + tag, mm["replication"]["response_divergence_pct"])
            floors.append(mm["replication"]["response_divergence_pct"])
            m("NVers" + tag, mm["n_versions"])
            for k, v in enumerate(mm["versions"]):
                lbl = "ABCDEF"[k]
                m("Res" + tag + lbl, v["resolved_pct"])
                m("Con" + tag + lbl, v["contract_pct"])
        # Checkpoint names are written once here so the manuscript cannot drift from the run.
        m("ShortMistral", "Mistral-7B-Instruct-v0.2")
        m("ShortPhi", "Phi-3-mini-4k-instruct")
        m("ShortDS", "deepseek-coder-6.7b-instruct")
        m("ShortQwen", "Qwen2.5-7B-Instruct")
        m("ShortLlama", "Meta-Llama-3-8B-Instruct")
        m("MaxNoiseFloor", max(floors))
        m("MinNoiseFloor", min(floors))
        m("NTasksExec", max(mm["n_tasks"] for mm in rq2["models"].values()))
        m("NFamily", len(rq2["family"]))
        m("NUninformative", rq2["n_uninformative_pairs"])
        m("NSigRes", rq2["n_family_sig_resolution"])
        m("NSigContract", rq2["n_family_sig_contract"])
        m("MistralRenderErr",
          rq2["models"]["mistral:7b-instruct-v0.2-q4_0"]["versions"][0]["render_errors"])

        def pair(model, i, j):
            return next(r for r in rq2["family"]
                        if r["model"] == model and r["i"] == i and r["j"] == j)

        def fmtp(x):
            return "%.4f" % x if x >= 0.0001 else "<0.0001"

        mi = pair("mistral:7b-instruct-v0.2-q4_0", 0, 1)
        m("MistralPHolmRes", fmtp(mi["p_holm_family"]))
        m("MistralPHolmCon", fmtp(mi["contract_p_holm_family"]))
        # Phi CI bounds for the two case-study transitions: the Threats claim that both intervals
        # lie on one side of zero is printed from these rather than asserted in words alone
        # (cr4 review panel, 2026-08-30).
        pci1, pci2 = pair("phi3:mini", 0, 1), pair("phi3:mini", 1, 2)
        m("PhiCIDownLo", pci1["ci_lo"])
        m("PhiCIDownHi", pci1["ci_hi"])
        m("PhiCIUpLo", pci2["ci_lo"])
        m("PhiCIUpHi", pci2["ci_hi"])
        m("MistralCILo", mi["ci_lo"])
        m("MistralCIHi", mi["ci_hi"])
        p1, p2 = pair("phi3:mini", 0, 1), pair("phi3:mini", 1, 2)
        m("PhiPHolmConDown", fmtp(p1["contract_p_holm_family"]))
        m("PhiPHolmConUp", fmtp(p2["contract_p_holm_family"]))
        m("PhiPHolmResDown", "%.3f" % p1["p_holm_family"])
        m("PhiPHolmResUp", "%.3f" % p2["p_holm_family"])
        pl = pair("phi3:mini", 0, 2)
        m("PhiFirstLastRes", "%.2f" % pl["p_holm_family"])

        m("NAllPairs", rq2["n_allpairs"])
        m("NAllSigRes", rq2["n_allpairs_sig_resolution"])
        m("NAllSigCon", rq2["n_allpairs_sig_contract"])
        for model, mm in rq2["models"].items():
            m("FloorDisc" + short.get(model, "M"), mm["replication"]["discordant_total"])
        m("QwenFloorP", "%.3f" % rq2["models"]["qwen2.5:7b-instruct"]["replication"]["p"])
        m("MistralDisc", pair("mistral:7b-instruct-v0.2-q4_0", 0, 1)["discordant_total"])
        m("PhiDiscDown", pair("phi3:mini", 0, 1)["discordant_total"])
        m("PhiDiscUp", pair("phi3:mini", 1, 2)["discordant_total"])

        tk = os.path.join(DATA, "tokenization.json")
        if os.path.exists(tk):
            with open(tk, encoding="utf-8") as fh:
                t = json.load(fh)
            m("NMarkersChecked", t["n_markers_checked"])
            # The prose says "at least \MarkerMinRatio{} times", so the displayed value must be
            # FLOORED to one decimal, never rounded: the true minimum is 1.75 (Mistral, 7/4) and
            # round() displayed 1.8, printing a lower bound larger than the measured minimum.
            # Caught independently by two cr4 reviewers (2026-08-30).
            m("MarkerMinRatio",
              math.floor(10 * min(r["tokens_as_characters"] / max(r["tokens_as_marker"], 1)
                                  for r in t["marker_probe"] if "skipped" not in r)) / 10)

        # ---- A7 system-free control ----
        psf = os.path.join(DATA, "rq2_systemfree.json")
        if os.path.exists(psf):
            with open(psf, encoding="utf-8") as fh:
                sf = json.load(fh)
            m("NSFEpisodes", sf["n_episodes"])
            m("NSFRenderErrors", sf["render_errors"])
            m("NSFFamily", len(sf["family"]))
            m("NSFSigRes", sf["n_family_sig_resolution"])
            m("NSFSigCon", sf["n_family_sig_contract"])
            for model, mm in sf["models"].items():
                tag = short.get(model, "M")
                m("SFFloor" + tag, mm["replication"]["response_divergence_pct"])
                for k, v in enumerate(mm["versions"]):
                    lbl = "ABCDEF"[k]
                    m("SFRes" + tag + lbl, v["resolved_pct"])
                    m("SFCon" + tag + lbl, v["contract_pct"])

            # The position-confound discriminator: how much does moving the contract into the user
            # turn change outcomes on templates that handle the system role CORRECTLY? If the
            # recovery were a position effect it would show up here too.
            # Shifts are computed from recovered task counts, not from differences of already
            # rounded percentages: on 60 tasks every true shift is a multiple of 1/60, and
            # 23.3 - 21.7 = 1.6 printed a value that cannot occur on that grid (the true shift
            # is 1/60 = 1.7 points). Caught by the cr2 review panel (2026-08-29).
            n_tasks = 60
            def _shift(pa: float, pb: float) -> float:
                ka = round(pa * n_tasks / 100.0)
                kb = round(pb * n_tasks / 100.0)
                return round(100.0 * abs(ka - kb) / n_tasks, 1)
            healthy = []
            for mod in ("mistral:7b-instruct-v0.2-q4_0", "phi3:mini"):
                for va, vb in zip(rq2["models"][mod]["versions"], sf["models"][mod]["versions"]):
                    if va["render_errors"] or va["contract_pct"] < 60.0:
                        continue  # this template mishandles the system role; it is the treatment
                    healthy.append((_shift(va["resolved_pct"], vb["resolved_pct"]),
                                    _shift(va["contract_pct"], vb["contract_pct"])))
            m("NHealthyTemplates", len(healthy))
            m("MaxHealthyResShift", round(max(h[0] for h in healthy), 1))
            m("MaxHealthyConShift", round(max(h[1] for h in healthy), 1))

        # ---- renderer validated on the HISTORICAL templates actually used ----
        hv = os.path.join(DATA, "historical_validation.json")
        if os.path.exists(hv):
            with open(hv, encoding="utf-8") as fh:
                h = json.load(fh)
            m("NHistChecked", h["n_checked"])
            m("NHistMismatch", h["n_mismatched"])

        ds = [r for r in rq2["family"] if r["model"] == "deepseek-coder:6.7b-instruct"]
        m("NDSPairs", len(ds))
        m("DSMinP", "%.2f" % min(r["p_holm_family"] for r in ds))

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote %s with %d macros" % (OUT, len(lines) - 3))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
