"""Write the tables and the generated prose fragments from the analysis outputs."""
from __future__ import annotations

import json
import os
import statistics

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
PAPER = os.path.join(ROOT, "paper")

# Uniformly abbreviated for column width: the Instruct token is dropped from every name, and the
# caption says so. Mixed truncation (two rows short, three long) was a cr3 proofreader finding;
# the full identifiers live in Section 3.4 and THIRD_PARTY.md.
SHORT = {"qwen2.5:7b-instruct": "Qwen2.5-7B",
         "phi3:mini": "Phi-3-mini-4k",
         "deepseek-coder:6.7b-instruct": "deepseek-coder-6.7b",
         "mistral:7b-instruct-v0.2-q4_0": "Mistral-7B-v0.2",
         "llama3:latest": "Meta-Llama-3-8B"}


GENERATED_HEADER = "% GENERATED by code/tables.py from the analysis output. Do not edit by hand.\n"


def w(name: str, text: str):
    """Write a generated fragment, stamped so the build gate can tell it apart from prose.

    The gate refuses bare numerals in the manuscript, because a typed number is one that can go
    stale. A file written from the analysis JSON cannot contain a typed number, so the gate skips
    the numeral check for files carrying this header, and separately asserts that every file it
    skips really does carry it.
    """
    with open(os.path.join(PAPER, name), "w", encoding="utf-8") as fh:
        fh.write(GENERATED_HEADER + text.rstrip() + "\n")
    print("wrote paper/%s" % name)


def diffsize(rq1: dict) -> dict:
    """Is the textual size of an edit any guide to whether it changes what the model sees?"""
    cos, beh = [], []
    zero_len_beh = 0
    for r in rq1["repos"]:
        for p in r.get("pairs", []):
            if not p["decidable"] or not p["textual_change"]:
                continue
            d = abs(p["len_after"] - p["len_before"])
            if p["behavioural"]:
                beh.append(d)
                if d == 0:
                    zero_len_beh += 1
            else:
                cos.append(d)
    # AUC of |len delta| as a behavioural-vs-cosmetic discriminator: the prose claims size is
    # "close to useless as a proxy" and the cr3 review panel (2026-08-30) asked for the
    # discrimination statistic backing that, computed from the same 273 decidable events.
    wins = ties = 0
    for a in beh:
        for b in cos:
            if a > b:
                wins += 1
            elif a == b:
                ties += 1
    auc = (wins + 0.5 * ties) / (len(beh) * len(cos)) if beh and cos else None
    out = {
        "n_cosmetic": len(cos), "n_behavioural": len(beh),
        "median_abs_len_cosmetic": int(statistics.median(cos)) if cos else 0,
        "median_abs_len_behavioural": int(statistics.median(beh)) if beh else 0,
        "max_abs_len_cosmetic": max(cos) if cos else 0,
        "max_abs_len_behavioural": max(beh) if beh else 0,
        "n_behavioural_zero_len_change": zero_len_beh,
        "auc_len_delta": round(auc, 3) if auc is not None else None,
    }
    with open(os.path.join(DATA, "diffsize.json"), "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=1)
    return out


def table_rq1(rq1: dict):
    s = rq1["summary"]
    rows = [
        ("Repositories in frame", r"\NFrame", ""),
        (r"\quad drifted (template changed at least once)", r"\NDrifted", r"\PctDrifted\%"),
        (r"\quad with a behavioural change", r"\NBehavioural", r"\PctBehFrame\%"),
        (r"\quad behavioural and settled ($>\SettledDays$ days)", r"\NBehSettled",
         r"\PctBehSettledFrame\%"),
        (r"\quad behavioural in a weight-silent interval", r"\NBehWeightSilent",
         r"\PctBehWeightSilent\% of beh."),
        ("Template-change events", r"\NEvents", ""),
        (r"\quad decidable", r"\NEventsDecidable", ""),
        (r"\quad behavioural", r"\NEventsBeh", r"\PctEventsBeh\% of dec."),
        (r"\quad cosmetic (renders identically)", r"\NEventsCosmetic", ""),
        (r"\quad undecidable (neither renders)", r"\NEventsUndecidable", ""),
        (r"\quad weight-silent", r"\NEventsWeightSilent", r"\PctEventsWeightSilent\%"),
    ]
    body = "\n".join(r"%s & %s & %s \\" % r for r in rows)
    w("tab_rq1.tex", r"""\begin{table}[t]
\caption{Chat-template drift in the frame. \emph{Behavioural} means the edit changes what the model
is shown, decided by rendering six fixed probe conversations through both templates.
\emph{Weight-silent} means no model-weight file changed in the interval, so a consumer who pinned
the model and verified its weights would have seen nothing.}
\label{tab:rq1}
\small
\begin{tabular}{lrr}
\toprule
 & count & share \\
\midrule
%s
\bottomrule
\end{tabular}
\end{table}""" % body)


def text_diffsize(d: dict):
    w("txt_diffsize.tex", r"""Textual diff size is close to useless as a proxy: as a discriminator
between behavioural and cosmetic edits, the absolute change in template length achieves an AUC of
\DiffAUC{}, barely above chance. The median absolute
change in template length is \MedAbsLenCosmetic{} characters for cosmetic edits and
\MedAbsLenBehavioural{} for behavioural ones, and the distributions overlap heavily: the largest
purely cosmetic edit in the frame changes \MaxCosmeticLenChange{} characters and alters nothing the
model sees, while \NBehZeroLenChange{} behavioural edits change the template's length by zero. A
reviewer skimming a diff for size will misclassify both tails, which is the argument for deciding
this by rendering.""")


def table_rq2(rq2: dict):
    lines = []
    order = ["mistral:7b-instruct-v0.2-q4_0", "phi3:mini", "deepseek-coder:6.7b-instruct",
             "qwen2.5:7b-instruct", "llama3:latest"]
    for model in order:
        m = rq2["models"][model]
        name, floor = SHORT.get(model, model), m["replication"]["response_divergence_pct"]
        for k, v in enumerate(m["versions"]):
            head = (r"%s & %s\%%" % (name, floor)) if k == 0 else " & "
            note = ""
            if v["render_errors"]:
                note = r"\,\textsuperscript{$\dagger$}"
            lines.append(r"%s & %s & %s\%%%s & %s\%% \\" % (
                head, v["date"], v["resolved_pct"], note, v["contract_pct"]))
        lines.append(r"\addlinespace")
    body = "\n".join(lines[:-1])
    w("tab_rq2.tex", r"""\begin{table}[t]
\caption{Same checkpoint, same conversation, same seed; only the historical chat template differs.
Checkpoint names drop their Instruct token for width; full identifiers are in
Section~\ref{sec:exec}.
\emph{Floor} is the response divergence between two runs of the \emph{same} template, a single
re-run of each checkpoint's first template: the serving stack's reproducibility noise for that
checkpoint. Resolution is the share of \NTasksExec{} repair tasks whose returned program passes its
test; contract is the share of replies obeying the stated output contract.
\textsuperscript{$\dagger$}~this template refuses the conversation outright: it raises on a system
message, so all \MistralRenderErr{} tasks fail before the model is reached.}
\label{tab:rq2}
\small
\begin{tabular}{lrlrr}
\toprule
checkpoint & floor & template & resolved & contract \\
\midrule
%s
\bottomrule
\end{tabular}
\end{table}""" % body)


def main() -> int:
    with open(os.path.join(DATA, "rq1.json"), encoding="utf-8") as fh:
        rq1 = json.load(fh)
    d = diffsize(rq1)
    table_rq1(rq1)
    text_diffsize(d)

    p2 = os.path.join(DATA, "rq2.json")
    if os.path.exists(p2):
        with open(p2, encoding="utf-8") as fh:
            rq2 = json.load(fh)
        table_rq2(rq2)
    else:
        print("rq2.json absent: RQ2 table not generated yet")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
